// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmY3APaCQde4wP8hl4dPMk59tDm9JNxZ8',
    appId: '1:842455681019:web:a71bc8baf6688e64e16d5e',
    messagingSenderId: '842455681019',
    projectId: 'bookaiapp',
    authDomain: 'bookaiapp.firebaseapp.com',
    storageBucket: 'bookaiapp.firebasestorage.app',
    measurementId: 'G-KE1LGJGEZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDJMXQT-T0ROLX6O960jGwrHpFfF58jyo',
    appId: '1:842455681019:android:254b65f005c9c68de16d5e',
    messagingSenderId: '842455681019',
    projectId: 'bookaiapp',
    storageBucket: 'bookaiapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdXDo-T223-KAMkkiv2Xh9megbtTmau9s',
    appId: '1:842455681019:ios:a605ca9ed773b83de16d5e',
    messagingSenderId: '842455681019',
    projectId: 'bookaiapp',
    storageBucket: 'bookaiapp.firebasestorage.app',
    iosBundleId: 'com.example.pulpscribe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdXDo-T223-KAMkkiv2Xh9megbtTmau9s',
    appId: '1:842455681019:ios:a605ca9ed773b83de16d5e',
    messagingSenderId: '842455681019',
    projectId: 'bookaiapp',
    storageBucket: 'bookaiapp.firebasestorage.app',
    iosBundleId: 'com.example.pulpscribe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmY3APaCQde4wP8hl4dPMk59tDm9JNxZ8',
    appId: '1:842455681019:web:6b0b4a6468241ee1e16d5e',
    messagingSenderId: '842455681019',
    projectId: 'bookaiapp',
    authDomain: 'bookaiapp.firebaseapp.com',
    storageBucket: 'bookaiapp.firebasestorage.app',
    measurementId: 'G-PC6VSSE1J9',
  );
}
